engine: huggingface
pipeline_task: image-text-to-text
model: meta-llama/Llama-4-Scout-17B-16E-Instruct
trust_remote_code: true              # needed to pull in Metas custom Llama4 classes
attn_implementation: flex_attention  # per the model card recomendation
system_prompt: >-
  You are good at counting items in images. Your task is to count the number of items in the image based on the question provided. You should only respond with the integer count, without any additional words or punctuation.
max_new_tokens: 20
batch_size: 1