# models/qwen-2.5-vl-7b-instruct.yaml
engine: huggingface
model: Qwen/Qwen2.5-VL-7B-Instruct     # HF repo ID for Qwen2.5 VL :contentReference[oaicite:4]{index=4}
#system_prompt: "You are Qwen, created by Alibaba Cloud. You are a helpful assistant." In the official doc they are ommiting the system propmpt
# system_prompt: >-
#   You are a vision-language evaluator. When asked “How many X”, respond with the integer count only.
system_prompt: >-
  You are good at counting items in images. Your task is to count the number of items in the image based on the question provided. You should only respond with the integer count, without any additional words or punctuation.
max_new_tokens: 20

batch_size: 1