# Qwen2.5-VL-3B-Instruct
engine: huggingface
model: Qwen/Qwen2.5-VL-3B-Instruct
system_prompt: >-
  You are good at counting items in images. Your task is to count the number of items in the image based on the question provided. You should only respond with the integer count, without any additional words or punctuation.
max_new_tokens: 20
do_sample: false
batch_size: 16