engine: anthropic
model: claude-3-5-haiku-20241022
system_prompt: >-
  You are good at counting items in images. Your task is to count the number of items in the image based on the question provided. You should only respond with the integer count, without any additional words or punctuation.
batch_size: 16