engine: google
model: gemini-2.5-flash-preview-04-17
system_prompt: >-
  You are a vision-language evaluator. When given an image and a question asking you to count items—phrases may vary (“How many”, “Count the number of”, “Number of”, etc.)—respond with the integer count only, with no additional words or punctuation.
batch_size: 600